package com.sun.crm.settings.mapper;

import com.sun.crm.settings.pojo.User;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;


public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Jun 02 21:57:36 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Jun 02 21:57:36 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Jun 02 21:57:36 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Jun 02 21:57:36 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Jun 02 21:57:36 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Jun 02 21:57:36 CST 2022
     */
    int updateByPrimaryKey(User record);


    /**
     * 通过结合中的账户、密码字段，查询user表格中的用户信息
     * @param map 使用map容器进行封装前端的请求
     * @return
     */
    User queryUserByUserActAndUserPwd(Map<String,Object> map);

    /**
     * 查询所有用户信息，封装为User，前台请求无需请求参数
     * @return
     */
    List<User> queryAllUsers();


    /*
    通过用户id查询用户信息
     */
    User queryById(String UserId);


}